"""empty message

Revision ID: 1c28dc63d801
Revises: e7259326badb
Create Date: 2017-11-12 15:27:34.911224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c28dc63d801'
down_revision = 'e7259326badb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Post', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Post', 'body_html')
    # ### end Alembic commands ###
