"""empty message

Revision ID: b65bc9380e42
Revises: cec211813953
Create Date: 2017-11-05 10:00:41.738987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65bc9380e42'
down_revision = 'cec211813953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
